FROM ubuntu:19.04 as builder
ARG bpftracesha
ARG bccversion
ARG libbpfsha

RUN apt-get update
RUN apt-get install -y libbpfcc-dev
RUN apt-get install -y bison cmake flex g++ git libelf-dev zlib1g-dev libfl-dev systemtap-sdt-dev
RUN apt-get install -y llvm-7-dev llvm-7-runtime libclang-7-dev clang-7
RUN git clone https://github.com/iovisor/bpftrace
RUN mkdir bpftrace/build 
WORKDIR /bpftrace/build
RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make -j8 bpftrace
RUN make install
